### ISSUE TITLE
ui can get screwed up when switching contexts

### ISSUE THREAD

**Issue by stripedpajamas** [stripedpajamas/scat#3]
there seems to be an issue with diffy when the messages array gets drastically filtered (switching between public and private contexts). I filed [an issue](https://github.com/mafintosh/diffy/issues/6) with mafintosh and in the meantime tried to workaround by having scat only fill up ~75% of the screen, but i'm not sure if the workaround is working around too well.

**Comment by stripedpajamas** [comment]
Trashed the 75% thing and did some math magic to keep messages from overflowing and causing the weird Diffy glitch. I don't think Diffy cares about what's off the top of the screen and that's what was screwing up the UI. 196f029b2fadaf3da2182e58f392eafec829bf3f

**Comment by cblgh** [comment]
@stripedpajamas hey did your math magic fix the ui glitches you were seeing? i'm having similar issues with [cabal](https://github.com/cabal-club/cabal) :)

**Comment by cblgh** [comment]
@stripedpajamas thanks for the response! 

i'll see if we can find the right mathemagic to fix this in cabal (or even fix it upstream in diffy... hmmmmm)
