### ISSUE TITLE
After a few seconds the screen fills with warning message

### ISSUE THREAD

**Issue by alanz** [stripedpajamas/scat#33]
See screenshot

![screenshot from 2018-09-16 14-06-03](https://user-images.githubusercontent.com/409607/45596275-f678cb80-b9b9-11e8-9adb-491b379514e0.png)

**Comment by stripedpajamas** [comment]
have you tried restarting sbot?

**Comment by alanz** [comment]
I did try that, and also starting it by itself, which also had the problem.

But I just ran it again now, and the problem does not occur.

I guess it was related to something to do with what was being synchronised by sbot at the time. Or the phase of the moon.

**Comment by stripedpajamas** [comment]
🤷🌙

**Comment by stripedpajamas** [comment]
might be worth "capturing" dependencies' logs and hiding them unless in debug mode. will investigate if that's an option.
