### ISSUE TITLE
Npm install warnings

### ISSUE THREAD

**Issue by lancew** [stripedpajamas/scat#37]
Receive following warnings when running npm instal:

```
$ npm install
npm WARN deprecated secure-scuttlebutt@18.6.0: WARNING: This project has been renamed to ssb-db. Install using ssb-db instead.
npm WARN deprecated nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.

```
When installing on Archlinux:
```
$ npm --version
6.4.1
$ node --version
v10.0.0

```

**Comment by stripedpajamas** [comment]
Good note @lancew 

Updated deps in ssb-chat-core here https://github.com/stripedpajamas/ssb-chat-core/commit/460c63c5509ad4209205359581d2c3dee0834f3b and am now doing some testing to make sure nothing broke. Not sure what is depending on nomnom so I'll have to dig into that a bit.

**Comment by lancew** [comment]
Sorry, I did intend and looking at it and doing a PR, but not got to it.

**Comment by stripedpajamas** [comment]
Have updated deps and don't get the secure-scuttlebutt deprecation warning
